name: Check ChromeDriver Version

on: [push]

jobs:
  check_chromedriver_version:
    runs-on: ubuntu-latest

    steps:
    - name: Setup ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(chromedriver --version)
        echo "Current ChromeDriver Version: $CHROMEDRIVER_VERSION"
